### ISSUE TITLE
Cannot use sqlite store in methods

### ISSUE THREAD

**Issue by marcelolopezh** [jepiqueau/vue-capacitor-data-storage-sqlite#1]
Hi! I have a question about the use of the sqlite store. I try to use it in the method section, but it doesn't recognize as a property. For example, when you click a button, the method to save the data is called, but when I do this I get an error in the browser "**TypeError: Cannot read property 'setItem' of undefined**". The same for when I try to open the storage "**Cannot read property 'openStore' of undefined**". If someone could guide me to solve these errors I would be completely grateful!

**Comment by jepiqueau** [comment]
@marcelolopezh Give me a bit more , can you share the code on github to reproduce as i do not really follow what you said. It seems that sqlite is not defined anymore.

**Comment by marcelolopezh** [comment]
I am trying when a button is pressed, it calls a function to store the data in sqlite. Obviously I am dealing with this simple example to be able to continue with the development of the project that I am creating.

This is the example code, it throws in first intance "**SQLiteStore.vue?3778:56 Uncaught (in promise) TypeError: Cannot read property 'openStore' of undefined**"

`<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button default-href="/home"></ion-back-button>
        </ion-buttons>
        <ion-title>SQLiteStore Test</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">SQLiteStore Test</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-card>
        <ion-card-content>
          <IonButton color="secondary" @click="showTesting()">Secondary</IonButton>
        </ion-card-content>
      </ion-card>
    </ion-content>
  </ion-page>
</template>
<script lang="ts">
import {
  IonContent,
  IonHeader,
  IonPage,
  IonTitle,
  IonToolbar,
  IonBackButton,
  IonButtons,
  IonButton,
  IonCard,
  IonCardContent,
} from "@ionic/vue";

import { defineComponent, getCurrentInstance, ref } from "vue";

export default defineComponent({
  name: "SQLiteStore",
  components: {
    IonContent,
    IonHeader,
    IonPage,
    IonTitle,
    IonToolbar,
    IonBackButton,
    IonButtons,
    IonButton,
    IonCard,
    IonCardContent,
  },
  methods: {
    async showTesting() {
      const app = getCurrentInstance();
      const storage = app?.appContext.config.globalProperties.$storage;

      const resOpen = await storage.openStore({});
      if (!resOpen) {
        console.log(" > Error \n");
        return;
      } else {
        // Store Json Object
        const data = { a: 20, b: "Hello World", c: { c1: 40, c2: "cool" } };
        await storage.setItem("testJson", JSON.stringify(data));
        const result = await storage.getItem("testJson");
        if (result !== JSON.stringify(data)) {
          console.log(" > SetItem/GetItem Json Object failed \n");
          return;
        }
        console.log(" > SetItem/GetItem Json Object successful \n");
      }
    },
  },
});
</script>`

**Comment by marcelolopezh** [comment]
I am trying when a button is pressed, it calls a function to store the data in sqlite. Obviously I am dealing with this simple example to be able to continue with the development of the project that I am creating.

This is the example code, it throws in first intance "**SQLiteStore.vue?3778:56 Uncaught (in promise) TypeError: Cannot read property 'openStore' of undefined**"


`<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button default-href="/home"></ion-back-button>
        </ion-buttons>
        <ion-title>SQLiteStore Test</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">SQLiteStore Test</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-card>
        <ion-card-content>
          <IonButton color="secondary" v-on:click="showTesting()">Secondary</IonButton>
        </ion-card-content>
      </ion-card>
    </ion-content>
  </ion-page>
</template>
<script>
import {
  IonContent,
  IonHeader,
  IonPage,
  IonTitle,
  IonToolbar,
  IonBackButton,
  IonButtons,
  IonButton,
  IonCard,
  IonCardContent,
} from "@ionic/vue";
import { defineComponent, getCurrentInstance } from "vue";
export default defineComponent({
  name: "SQLiteStore",
  components: {
    IonContent,
    IonHeader,
    IonPage,
    IonTitle,
    IonToolbar,
    IonBackButton,
    IonButtons,
    IonButton,
    IonCard,
    IonCardContent,
  },
  methods: {
    async showTesting() {
      const app = getCurrentInstance();
      const storage = app?.appContext.config.globalProperties.$storage;
      const resOpen = await storage.openStore({});
      if (!resOpen) {
        console.log(" > Error \n");
        return;
      } else {
        // Store Json Object
        const data = { a: 20, b: "Hello World", c: { c1: 40, c2: "cool" } };
        await storage.setItem("testJson", JSON.stringify(data));
        const result = await storage.getItem("testJson");
        if (result !== JSON.stringify(data)) {
          console.log(" > SetItem/GetItem Json Object failed \n");
          return;
        }
        console.log(" > SetItem/GetItem Json Object successful \n");
      }
    },
  },
});
</script>`

**Comment by marcelolopezh** [comment]
I am trying that when pressing a button, the information is saved in sqlite. Obviously I am testing how I could do it with this simple example. In the real project I have to rescue the information from a form to save it in sqlite. But I have not been able to move forward since I get the error "**Uncaught (in promise) TypeError: Cannot read property 'openStore' of undefined**"

```  
<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button default-href="/home"></ion-back-button>
        </ion-buttons>
        <ion-title>SQLiteStore Test</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">SQLiteStore Test</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-card>
        <ion-card-content>
          <IonButton color="secondary" v-on:click="showTesting()"
            >Secondary</IonButton
          >
        </ion-card-content>
      </ion-card>
    </ion-content>
  </ion-page>
</template>

<script>
import {
  IonContent,
  IonHeader,
  IonPage,
  IonTitle,
  IonToolbar,
  IonBackButton,
  IonButtons,
  IonButton,
  IonCard,
  IonCardContent,
} from "@ionic/vue";
import { defineComponent, getCurrentInstance } from "vue";
export default defineComponent({
  name: "SQLiteStore",
  components: {
    IonContent,
    IonHeader,
    IonPage,
    IonTitle,
    IonToolbar,
    IonBackButton,
    IonButtons,
    IonButton,
    IonCard,
    IonCardContent,
  },
  methods: {
    async showTesting() {
      const app = getCurrentInstance();
      const storage = app?.appContext.config.globalProperties.$storage;
      const resOpen = await storage.openStore({});
      if (!resOpen) {
        console.log(" > Error \n");
        return;
      } else {
        // Store Json Object
        const data = { a: 20, b: "Hello World", c: { c1: 40, c2: "cool" } };
        await storage.setItem("testJson", JSON.stringify(data));
        const result = await storage.getItem("testJson");
        if (result !== JSON.stringify(data)) {
          console.log(" > SetItem/GetItem Json Object failed \n");
          return;
        }
        console.log(" > SetItem/GetItem Json Object successful \n");
      }
    },
  },
});
</script>

<style scoped>
ion-card-content {
  font-size: 1.5rem !important;
}
</style>
```

**Comment by jepiqueau** [comment]
@marcelolopezh 
Use the setup() method like this:
```ts
<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button default-href="/home"></ion-back-button>
        </ion-buttons>
        <ion-title>SQLiteStore Test</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">SQLiteStore Test</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-card>
        <ion-card-content>
          <IonButton color="secondary" v-on:click="showTesting()"
            >Secondary</IonButton
          >
        </ion-card-content>
      </ion-card>
    </ion-content>
  </ion-page>
</template>

<script>
import {
  IonContent,
  IonHeader,
  IonPage,
  IonTitle,
  IonToolbar,
  IonBackButton,
  IonButtons,
  IonButton,
  IonCard,
  IonCardContent,
} from "@ionic/vue";
import { defineComponent, getCurrentInstance } from "vue";
export default defineComponent({
  name: "TestIssue1",
  components: {
    IonContent,
    IonHeader,
    IonPage,
    IonTitle,
    IonToolbar,
    IonBackButton,
    IonButtons,
    IonButton,
    IonCard,
    IonCardContent,
  },
  setup() {
    const app = getCurrentInstance();
    const storage = app?.appContext.config.globalProperties.$storage;
    const showTesting = async () => {
      const resOpen = await storage.openStore({});
      if (!resOpen) {
        console.log(" > Error \n");
        return;
      } else {
        // Store Json Object
        const data = { a: 20, b: "Hello World", c: { c1: 40, c2: "cool" } };
        await storage.setItem("testJson", JSON.stringify(data));
        const result = await storage.getItem("testJson");
        if (result !== JSON.stringify(data)) {
          console.log(" > SetItem/GetItem Json Object failed \n");
          return;
        }
        console.log(" > SetItem/GetItem Json Object successful \n");
      }

    };
    return {showTesting};
  },
});
</script>

<style scoped>
ion-card-content {
  font-size: 1.5rem !important;
}
</style>
```
and it will work

**Comment by jepiqueau** [comment]
@marcelolopezh you can also do this if you like to use method:
```
<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button default-href="/home"></ion-back-button>
        </ion-buttons>
        <ion-title>SQLiteStore Test</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">SQLiteStore Test</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-card>
        <ion-card-content>
          <IonButton color="secondary" v-on:click="showTesting(storage)"
            >Secondary</IonButton
          >
        </ion-card-content>
      </ion-card>
    </ion-content>
  </ion-page>
</template>

<script>
import {
  IonContent,
  IonHeader,
  IonPage,
  IonTitle,
  IonToolbar,
  IonBackButton,
  IonButtons,
  IonButton,
  IonCard,
  IonCardContent,
} from "@ionic/vue";
import { defineComponent, getCurrentInstance } from "vue";
export default defineComponent({
  name: "TestIssue1",
  components: {
    IonContent,
    IonHeader,
    IonPage,
    IonTitle,
    IonToolbar,
    IonBackButton,
    IonButtons,
    IonButton,
    IonCard,
    IonCardContent,
  },
  setup() {
    const app = getCurrentInstance();
    const storage = app?.appContext.config.globalProperties.$storage;
   return {storage};
  },
  methods: {
    async showTesting(storage) {
      const resOpen = await storage.openStore({});
      if (!resOpen) {
        console.log(" > Error \n");
        return;
      } else {
        // Store Json Object
        const data = { a: 20, b: "Hello World", c: { c1: 40, c2: "cool" } };
        await storage.setItem("testJson", JSON.stringify(data));
        const result = await storage.getItem("testJson");
        if (result !== JSON.stringify(data)) {
          console.log(" > SetItem/GetItem Json Object failed \n");
          return;
        }
        console.log(" > SetItem/GetItem Json Object successful \n");
      }
    },
  },

});
</script>

<style scoped>
ion-card-content {
  font-size: 1.5rem !important;
}
</style>
```

**Comment by jepiqueau** [comment]
@marcelolopezh see https://github.com/jepiqueau/vue-capacitor-data-storage-sqlite
